name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: check path
      run: pwd
    - name: list files
      run: ls -la
    - name: test
      run: make test
