name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: macos-latest
    steps:
    - name: Debug info
      run: clang++ -v
    - name: Checkout code
      uses: actions/checkout@v2
    - name: test
      run: make test
